services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    environment:
      - JVM_INITIAL_RAM_PERCENT=60.0
      - JVM_MAX_RAM_PERCENT=85.0
    volumes:
      - ./data/SMP:/app/world
      - ./data/SMP_nether:/app/world_nether
      - ./data/SMP_the_end:/app/world_the_end
      - ./data/server.properties:/app/server.properties
      - ./data/server-icon.png:/app/server-icon.png
      - ./data/ops.json:/app/ops.json
      - ./data/plugins:/app/plugins
    restart: unless-stopped
