services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - ./data/SMP:/app/world
      - ./data/server.properties:/app/server.properties
      - ./data/ops.json:/app/ops.json
      - ./data/plugins:/app/plugins
    restart: unless-stopped
