#!/usr/bin/env bash
set -euo pipefail

# DockerCraft SMP - Quick Start Script
# One-command setup for new servers

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     🎮 DockerCraft SMP - Quick Start Script               ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check prerequisites
echo "🔍 Checking prerequisites..."

if ! command -v docker &> /dev/null; then
    echo -e "${RED}❌ Docker not found. Please install Docker first:${NC}"
    echo "   https://docs.docker.com/get-docker/"
    exit 1
fi

if ! command -v docker-compose &> /dev/null; then
    echo -e "${RED}❌ Docker Compose not found. Please install Docker Compose:${NC}"
    echo "   https://docs.docker.com/compose/install/"
    exit 1
fi

echo -e "${GREEN}✅ Docker and Docker Compose found${NC}"

# Check if server.jar exists
if [[ ! -f "server.jar" ]]; then
    echo -e "${YELLOW}⚠️  server.jar not found!${NC}"
    echo ""
    echo "Please download a Minecraft server JAR (version 1.21.8) and place it in this directory."
    echo ""
    echo "Recommended download command:"
    echo "  curl -L -o server.jar https://api.papermc.io/v2/projects/paper/versions/1.21.8/builds/latest/downloads/paper-1.21.8-latest.jar"
    echo ""
    echo "Alternative sources:"
    echo "  • Paper: https://papermc.io/downloads (recommended)"
    echo "  • Spigot: https://www.spigotmc.org/"
    echo "  • Vanilla: https://www.minecraft.net/en-us/download/server"
    echo ""
    exit 1
fi

echo -e "${GREEN}✅ server.jar found${NC}"

# Create necessary directories
echo ""
echo "📁 Creating directories..."
mkdir -p data/SMP data/SMP_nether data/SMP_the_end data/plugins

# Check if first run
if [[ ! -f "data/server.properties" ]]; then
    echo ""
    echo "⚙️  First time setup detected!"
    echo ""

    # Ask for configuration
    read -p "📝 Enter server name (default: SMP Realm): " SERVER_NAME
    SERVER_NAME=${SERVER_NAME:-"SMP Realm"}

    read -p "👥 Enter max players (default: 20): " MAX_PLAYERS
    MAX_PLAYERS=${MAX_PLAYERS:-20}

    read -p "🎮 Enter game mode [survival/creative/adventure] (default: survival): " GAMEMODE
    GAMEMODE=${GAMEMODE:-survival}

    read -p "💀 Enter difficulty [peaceful/easy/normal/hard] (default: easy): " DIFFICULTY
    DIFFICULTY=${DIFFICULTY:-easy}

    # Create server.properties
    cat > data/server.properties <<EOF
#Minecraft server properties
#Generated by DockerCraft Quick Start
server-port=25565
gamemode=$GAMEMODE
force-gamemode=false
difficulty=$DIFFICULTY
allow-nether=true
max-players=$MAX_PLAYERS
online-mode=false
white-list=false
enforce-whitelist=false
motd=\u00A76\u00A7l$SERVER_NAME\u00A7r\n\u00A7eA DockerCraft SMP Server
spawn-protection=16
view-distance=8
simulation-distance=6
EOF

    echo -e "${GREEN}✅ Configuration saved${NC}"
else
    echo -e "${GREEN}✅ Existing configuration found${NC}"
fi

echo ""
echo "🚀 Starting Minecraft server..."
docker-compose up -d --build

echo ""
echo "⏳ Waiting for server to start..."
sleep 5

# Check if container is running
if docker-compose ps | grep -q "Up"; then
    echo ""
    echo -e "${GREEN}✅ Server is running!${NC}"
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    echo "🎮 Connect to your server:"
    echo ""
    echo "   localhost:25565"
    echo ""
    echo "📊 View logs:"
    echo "   docker-compose logs -f"
    echo ""
    echo "🛑 Stop server:"
    echo "   docker-compose down"
    echo ""
    echo "💾 Create backup:"
    echo "   ./backup_data.sh"
    echo ""
    echo "📚 Documentation:"
    echo "   ./docs/"
    echo ""
    echo "═══════════════════════════════════════════════════════════"
else
    echo -e "${RED}❌ Server failed to start. Check logs:${NC}"
    echo "   docker-compose logs"
    exit 1
fi
